---
es_node_quorum: "{{ (openshift_logging_es_cluster_size | int/2 | round(0,'floor') + 1) | int}}"
es_recover_expected_nodes: "{{openshift_logging_es_cluster_size | int}}"
es_ops_node_quorum: "{{ (openshift_logging_es_ops_cluster_size | int/2 | round(0,'floor') + 1) | int}}"
es_ops_recover_expected_nodes: "{{openshift_logging_es_ops_cluster_size | int}}"

es_log_appenders: ['file', 'console']

__default_logging_ops_projects: ['default', 'openshift', 'openshift-infra', 'kube-system', 'openshift-logging']

__default_openshift_logging:
  cluster_names: ['es']
  aggregators: ['fluentd']
  fluentd:
    namespace: openshift-logging
    nodeselector: {'logging-infra-fluentd': 'true'}
    master_url: "https://kubernetes.default.svc.{{ openshift.common.dns_domain }}"
    master_public_url: "{{ 'https://' + openshift_master_cluster_public_hostname | default(openshift.common.public_hostname, true) + ':' ~ openshift_master_api_port }}"
    cpu_limit: null
    cpu_request: 100m
    memory_limit: 512Mi
    journal_source: ""
    journal_read_from_head: ""
    hosts: ['--all']
    buffer_queue_limit: 32
    buffer_size_limit: 8m
    app:
      host: logging-es
      port: 9200
      client_cert: /etc/fluent/keys/cert
      client_key: /etc/fluent/keys/key
      ca: /etc/fluent/keys/ca

    infra:
      host: logging-es
      port: 9200
      client_cert: /etc/fluent/keys/infra-cert
      client_key: /etc/fluent/keys/infra-key
      ca: /etc/fluent/keys/infra-ca

  mux:
    allow_external: False
    use_mux: "{{ openshift_logging_mux_allow_external | default(False) }}"
    hostname: "{{ 'mux.' ~ openshift_master_default_subdomain}}"
    port: 24284
    cpu_limit: null
    memory_limit: 512Mi
    cpu_request: 100m
    # the namespace to use for undefined projects - users will typically not need to set this
    # extra namespaces to create for mux clients - users will need to set this
    namespaces: []

  es:
    install: False
    namespace: openshift-logging
    master_url: "https://kubernetes.default.svc.{{ openshift.common.dns_domain }}"
    master_public_url: "{{ 'https://' + openshift_master_cluster_public_hostname | default(openshift.common.public_hostname, true) + ':' ~ openshift_master_api_port }}"
    nodeselector: null
    labels: {}
    purge_logging: False
    image_pull_secret: ""

    curator:
      default_days: 30
      run_hour: 3
      run_minute: 30
      run_timezone: UTC
      timeout: 300
      script_log_level: INFO
      log_error: ERROR
      cpu_limit: null
      cpu_request: 100m
      memory_limit: 256Mi
      node_selector: {}

    kibana:
      hostname: "{{ 'kibana.' ~ openshift_master_default_subdomain }}"
      cpu_limit: null
      cpu_request: 100m
      memory_limit: 736Mi
      replica_count: 1
      edge_term_policy: Redirect
      nodeselector: {}
      cert: ""
      key: ""
      ca: ""
      proxy:
        debug: false
        cpu_limit: null
        cpu_request: 100m
        memory_limit: 256Mi

    elasticsearch:
      host: logging-es
      port: 9200
      ca: /etc/fluent/keys/ca
      client_cert: /etc/fluent/keys/cert
      client_key: /etc/fluent/keys/key
      cluster_size: 1
      cpu_limit: null
      cpu_request: "1"
      # the logging appenders for the root loggers to write ES logs. Valid values: 'file', 'console'
      log_appenders: ['file']
      memory_limit: "8Gi"
      pv_selector: "{{ openshift_logging_storage_labels | default('') }}"
      pvc_dynamic: "{{ openshift_logging_elasticsearch_pvc_dynamic | default(False) }}"
      pvc_size: ''
      pvc_prefix: "logging-es"
      recover_after_time: 5m
      storage_group: "65534"
      nodeselector: {}
      # openshift_logging_es_config is a hash to be merged into the defaults for the elasticsearch.yaml
      config: {}

      # for exposing es to external (outside of the cluster) clients
      allow_external: False
      hostname: "{{ 'es.' ~ openshift_master_default_subdomain }}"

      #The absolute path on the control node to the cert file to use
      #for the public facing es certs
      cert: ""

      #The absolute path on the control node to the key file to use
      #for the public facing es certs
      key: ""

      #The absolute path on the control node to the CA file to use
      #for the public facing es certs
      ca_ext: ""

      # allow cluster-admin or cluster-reader to view operations index
      # This is really only applicable for your infra cluster
      allow_cluster_reader: False
