---
# Vars for when this is called:
# __component is the variable to use when pulling out variables
# __component will be set to be openshift_logging.fluentd or openshift_logging.mux, etc
# __cluster_name is the name of that component -- fluentd, mux, etc


## Fluentd
- when: openshift_logging.fluentd.install | default(True) | bool
  import_role:
    name: openshift_logging_fluentd
  vars:
    generated_certs_dir: "{{openshift.common.config_base}}/logging"
